// Top universities in the USA and prominent international institutions
export const UNIVERSITIES = [
  // Ivy League
  "Harvard University",
  "Yale University",
  "Princeton University",
  "Columbia University",
  "University of Pennsylvania",
  "Brown University",
  "Dartmouth College",
  "Cornell University",

  // Top Public Universities
  "University of California, Berkeley",
  "University of California, Los Angeles",
  "University of California, San Diego",
  "University of California, Irvine",
  "University of California, Davis",
  "University of California, Santa Barbara",
  "University of California, Riverside",
  "University of California, Santa Cruz",
  "University of California, Merced",
  "University of Michigan",
  "University of Virginia",
  "University of North Carolina at Chapel Hill",
  "University of Texas at Austin",
  "University of Wisconsin-Madison",
  "University of Illinois at Urbana-Champaign",
  "University of Washington",
  "Georgia Institute of Technology",
  "University of Florida",
  "Ohio State University",
  "University of Maryland",
  "Pennsylvania State University",
  "Purdue University",
  "University of Minnesota",
  "Rutgers University",
  "Texas A&M University",
  "University of Georgia",
  "University of Pittsburgh",
  "University of Iowa",
  "Indiana University",
  "University of Colorado Boulder",
  "University of Arizona",
  "Arizona State University",
  "Michigan State University",
  "University of Connecticut",
  "University of Delaware",
  "University of Massachusetts Amherst",
  "Stony Brook University",
  "University at Buffalo",
  "Binghamton University",

  // Top Private Universities
  "Stanford University",
  "Massachusetts Institute of Technology",
  "California Institute of Technology",
  "Duke University",
  "Northwestern University",
  "Johns Hopkins University",
  "University of Chicago",
  "Rice University",
  "Vanderbilt University",
  "Washington University in St. Louis",
  "Emory University",
  "Carnegie Mellon University",
  "University of Notre Dame",
  "Georgetown University",
  "University of Southern California",
  "Wake Forest University",
  "Tufts University",
  "Boston College",
  "New York University",
  "University of Rochester",
  "Case Western Reserve University",
  "Rensselaer Polytechnic Institute",
  "Lehigh University",
  "Syracuse University",
  "Northeastern University",
  "Boston University",
  "Brandeis University",
  "Tulane University",
  "University of Miami",

  // State Flagships & Major Universities
  "University of Alabama",
  "University of Alaska",
  "University of Arkansas",
  "University of Hawaii",
  "University of Idaho",
  "University of Kansas",
  "University of Kentucky",
  "Louisiana State University",
  "University of Maine",
  "University of Mississippi",
  "University of Missouri",
  "University of Montana",
  "University of Nebraska",
  "University of Nevada, Las Vegas",
  "University of Nevada, Reno",
  "University of New Hampshire",
  "University of New Mexico",
  "University of North Dakota",
  "University of Oklahoma",
  "University of Oregon",
  "Oregon State University",
  "University of Rhode Island",
  "University of South Carolina",
  "University of South Dakota",
  "University of Tennessee",
  "University of Utah",
  "University of Vermont",
  "University of Wyoming",
  "West Virginia University",

  // California State Universities
  "San Diego State University",
  "San Francisco State University",
  "San Jose State University",
  "California State University, Long Beach",
  "California State University, Fullerton",
  "California State University, Northridge",
  "California Polytechnic State University",
  "California State Polytechnic University, Pomona",

  // SUNY Schools
  "University at Albany",
  "Binghamton University",
  "University at Buffalo",
  "Stony Brook University",

  // Notable Tech/Engineering Schools
  "Harvey Mudd College",
  "Olin College of Engineering",
  "Rose-Hulman Institute of Technology",
  "Worcester Polytechnic Institute",
  "Stevens Institute of Technology",
  "Colorado School of Mines",
  "Illinois Institute of Technology",

  // Liberal Arts Colleges
  "Williams College",
  "Amherst College",
  "Swarthmore College",
  "Wellesley College",
  "Pomona College",
  "Bowdoin College",
  "Carleton College",
  "Claremont McKenna College",
  "Middlebury College",
  "Grinnell College",
  "Haverford College",
  "Davidson College",
  "Vassar College",
  "Colby College",
  "Hamilton College",
  "Smith College",
  "Colgate University",
  "Oberlin College",
  "Macalester College",
  "Bates College",
  "Bryn Mawr College",
  "Reed College",

  // Business Schools
  "Babson College",
  "Bentley University",

  // Southern Universities
  "University of North Carolina",
  "North Carolina State University",
  "Duke University",
  "Clemson University",
  "University of South Carolina",
  "College of Charleston",
  "University of Tennessee",
  "Auburn University",
  "University of Alabama",
  "Florida State University",
  "University of Central Florida",
  "University of South Florida",

  // Midwest Universities
  "Washington University in St. Louis",
  "University of Chicago",
  "Northwestern University",
  "University of Notre Dame",
  "Marquette University",
  "DePaul University",
  "Loyola University Chicago",
  "University of Dayton",
  "Miami University",
  "Ohio University",
  "University of Cincinnati",
  "University of Akron",
  "Kent State University",
  "Bowling Green State University",
  "Northern Illinois University",
  "Western Michigan University",
  "Central Michigan University",
  "Eastern Michigan University",

  // Western Universities
  "University of Denver",
  "Colorado State University",
  "University of New Mexico",
  "New Mexico State University",
  "Brigham Young University",
  "University of Wyoming",
  "Montana State University",
  "Idaho State University",
  "Boise State University",

  // Texas Universities
  "University of Texas at Dallas",
  "University of Texas at San Antonio",
  "University of Texas at Arlington",
  "University of Texas at El Paso",
  "Texas Tech University",
  "Texas Christian University",
  "Baylor University",
  "Southern Methodist University",
  "University of Houston",
  "Rice University",

  // New York Universities
  "Cornell University",
  "Columbia University",
  "New York University",
  "Fordham University",
  "St. John's University",
  "Hofstra University",
  "Pace University",
  "The New School",
  "Pratt Institute",
  "Parsons School of Design",
  "School of Visual Arts",
  "Cooper Union",

  // Pennsylvania Universities
  "University of Pennsylvania",
  "Carnegie Mellon University",
  "Drexel University",
  "Temple University",
  "Villanova University",
  "Duquesne University",
  "Lafayette College",
  "Bucknell University",

  // Massachusetts Universities
  "Harvard University",
  "MIT",
  "Tufts University",
  "Boston University",
  "Boston College",
  "Northeastern University",
  "Brandeis University",
  "University of Massachusetts Amherst",
  "Worcester Polytechnic Institute",
  "Amherst College",
  "Williams College",
  "Smith College",
  "Wellesley College",

  // International Universities (Major Names)
  "University of Oxford",
  "University of Cambridge",
  "Imperial College London",
  "London School of Economics",
  "University College London",
  "King's College London",
  "University of Edinburgh",
  "University of Manchester",
  "University of Toronto",
  "McGill University",
  "University of British Columbia",
  "University of Waterloo",
  "ETH Zurich",
  "EPFL",
  "Technical University of Munich",
  "Ludwig Maximilian University of Munich",
  "Heidelberg University",
  "Humboldt University of Berlin",
  "University of Amsterdam",
  "Delft University of Technology",
  "Leiden University",
  "Utrecht University",
  "Karolinska Institute",
  "Lund University",
  "Uppsala University",
  "University of Copenhagen",
  "University of Melbourne",
  "Australian National University",
  "University of Sydney",
  "University of Queensland",
  "Monash University",
  "University of Auckland",
  "National University of Singapore",
  "Nanyang Technological University",
  "University of Hong Kong",
  "Tsinghua University",
  "Peking University",
  "University of Tokyo",
  "Kyoto University",
  "Seoul National University",
  "KAIST",
  "Indian Institute of Technology Bombay",
  "Indian Institute of Technology Delhi",
  "Indian Institute of Technology Madras",
  "Indian Institute of Technology Kanpur",
  "Sorbonne University",
  "Sciences Po",
  "École Polytechnique",
].sort();

export const DEGREE_TYPES = [
  "Associate's",
  "Bachelor's",
  "B.A.",
  "B.S.",
  "B.Eng.",
  "B.F.A.",
  "B.Arch.",
  "B.B.A.",
  "Master's",
  "M.A.",
  "M.S.",
  "M.Eng.",
  "M.B.A.",
  "M.F.A.",
  "M.Arch.",
  "M.Ed.",
  "M.P.H.",
  "M.P.A.",
  "M.S.W.",
  "M.P.P.",
  "LL.M.",
  "Ph.D.",
  "Ed.D.",
  "D.B.A.",
  "M.D.",
  "J.D.",
  "D.O.",
  "Pharm.D.",
  "D.V.M.",
  "D.D.S.",
  "D.M.D.",
  "Psy.D.",
  "D.P.T.",
  "Au.D.",
  "Sc.D.",
].sort();

export const PROGRAM_NAMES = [
  // STEM Programs
  "Computer Science",
  "Computer Engineering",
  "Software Engineering",
  "Data Science",
  "Information Systems",
  "Information Technology",
  "Artificial Intelligence",
  "Machine Learning",
  "Cybersecurity",
  "Electrical Engineering",
  "Mechanical Engineering",
  "Chemical Engineering",
  "Civil Engineering",
  "Biomedical Engineering",
  "Aerospace Engineering",
  "Industrial Engineering",
  "Environmental Engineering",
  "Materials Science",
  "Mathematics",
  "Applied Mathematics",
  "Statistics",
  "Physics",
  "Applied Physics",
  "Chemistry",
  "Biochemistry",
  "Biology",
  "Molecular Biology",
  "Biotechnology",
  "Neuroscience",
  "Bioinformatics",

  // Business & Management
  "Business Administration",
  "Management",
  "Finance",
  "Accounting",
  "Marketing",
  "Operations Management",
  "Supply Chain Management",
  "Human Resources",
  "Organizational Behavior",
  "Entrepreneurship",
  "International Business",
  "Business Analytics",
  "Real Estate",
  "Hospitality Management",

  // Social Sciences
  "Economics",
  "Psychology",
  "Sociology",
  "Political Science",
  "International Relations",
  "Anthropology",
  "Geography",
  "Urban Planning",
  "Public Policy",
  "Public Administration",
  "Social Work",
  "Criminal Justice",
  "Education",
  "Educational Leadership",

  // Humanities
  "English",
  "Literature",
  "History",
  "Philosophy",
  "Religious Studies",
  "Classics",
  "Linguistics",
  "Foreign Languages",
  "Spanish",
  "French",
  "German",
  "Chinese",
  "Japanese",

  // Arts & Design
  "Fine Arts",
  "Studio Art",
  "Graphic Design",
  "Industrial Design",
  "Fashion Design",
  "Interior Design",
  "Architecture",
  "Landscape Architecture",
  "Urban Design",
  "Film Studies",
  "Film Production",
  "Theater",
  "Music",
  "Music Performance",
  "Music Composition",
  "Dance",
  "Photography",

  // Communication & Media
  "Communications",
  "Journalism",
  "Public Relations",
  "Media Studies",
  "Advertising",
  "Digital Media",

  // Health Sciences
  "Nursing",
  "Public Health",
  "Health Administration",
  "Epidemiology",
  "Biostatistics",
  "Kinesiology",
  "Nutrition",
  "Pharmacy",
  "Physical Therapy",
  "Occupational Therapy",
  "Speech Pathology",

  // Law & Legal Studies
  "Law",
  "Legal Studies",
  "Intellectual Property",
  "Tax Law",
  "Corporate Law",
  "Environmental Law",

  // Environmental & Earth Sciences
  "Environmental Science",
  "Environmental Studies",
  "Sustainability",
  "Geology",
  "Geoscience",
  "Atmospheric Science",
  "Oceanography",
  "Ecology",

  // Other Professional Programs
  "Library Science",
  "Information Science",
  "Sports Management",
  "Recreation Management",
  "Agricultural Science",
  "Food Science",
  "Veterinary Medicine",
].sort();

